name: CalcTestJava

env:
  TESTOPS_ENDPOINT: https://demo.qatools.cloud/
  TESTOPS_PROJECT_ID: 166
  TESTOPS_TOKEN: ${{ secrets.TESTOPS_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  RESULTS: "target/allure-results"
  BROWSER: ${{ inputs.BROWSER || 'OperaGX' }}
  OS: ${{ inputs.OS || 'Win_11' }}
  BRANCH: ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      BROWSER:
        description: Browser
        required: false
        default: "OperaGX"
      OS:
        description: OS
        required: false
        default: "Win_11"
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
        required: false
        default: ""
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME - service parameter (leave blank)"
        required: false
        default: ""

jobs:
  autotests:
    name: Run Java tests with Allure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Установка allurectl — связующее звено с TestOps
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.TESTOPS_ENDPOINT }}
          allure-token: ${{ env.TESTOPS_TOKEN }}
          allure-project-id: ${{ env.TESTOPS_PROJECT_ID }}

      - name: Create results directory
        run: mkdir -p $RESULTS

      - name: Run tests and report to TestOps
        run: |
          allurectl watch -- mvn clean test -Dallure.results.directory=$RESULTS
        continue-on-error: true
        env:
          ALLURE_RESULTS: $RESULTS

      - name: List results
        if: always()
        run: ls -la $RESULTS

      - name: Upload allure results to TestOps manually
        if: always()
        run: |
          allurectl upload $RESULTS